[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "quant_backtest"
version = "0.0.1"
dependencies = [
    "joblib",
    "numpy",
    "pandas",
    "matplotlib"
]

[tool.setuptools.packages.find]
where = ["."]
include = ["*"]
exclude = ["asset"]
